# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.distInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.distInput.setObjectName("distInput")
        self.gridLayout.addWidget(self.distInput, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.planInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.planInput.setObjectName("planInput")
        self.gridLayout.addWidget(self.planInput, 1, 1, 1, 1)
        self.corrInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.corrInput.setObjectName("corrInput")
        self.gridLayout.addWidget(self.corrInput, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.trafInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.trafInput.setObjectName("trafInput")
        self.gridLayout.addWidget(self.trafInput, 4, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Y0Input = QtWidgets.QLineEdit(self.layoutWidget)
        self.Y0Input.setInputMask("")
        self.Y0Input.setText("")
        self.Y0Input.setFrame(True)
        self.Y0Input.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Y0Input.setDragEnabled(False)
        self.Y0Input.setReadOnly(False)
        self.Y0Input.setClearButtonEnabled(False)
        self.Y0Input.setObjectName("Y0Input")
        self.gridLayout_2.addWidget(self.Y0Input, 0, 1, 1, 1)
        self.X0Input = QtWidgets.QLineEdit(self.layoutWidget)
        self.X0Input.setText("")
        self.X0Input.setObjectName("X0Input")
        self.gridLayout_2.addWidget(self.X0Input, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.betaLInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.betaLInput.setPlaceholderText("")
        self.betaLInput.setObjectName("betaLInput")
        self.horizontalLayout.addWidget(self.betaLInput)
        self.betaRInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.betaRInput.setEnabled(False)
        self.betaRInput.setObjectName("betaRInput")
        self.horizontalLayout.addWidget(self.betaRInput)
        self.betaStep = QtWidgets.QLineEdit(self.layoutWidget)
        self.betaStep.setEnabled(False)
        self.betaStep.setObjectName("betaStep")
        self.horizontalLayout.addWidget(self.betaStep)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.calculateButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calculateButton.setFont(font)
        self.calculateButton.setObjectName("calculateButton")
        self.verticalLayout.addWidget(self.calculateButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.checkBox, self.calculateButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "Auto"))
        self.label_5.setText(_translate("MainWindow", "Traffic function z(t)"))
        self.label.setText(_translate("MainWindow", "Planned shows number S(t)"))
        self.label_3.setText(_translate("MainWindow", "Correction function f(z, x, S, b)"))
        self.label_6.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Distribution p(w)"))
        self.label_4.setText(_translate("MainWindow", "Beta (b)"))
        self.Y0Input.setPlaceholderText(_translate("MainWindow", "Y0"))
        self.X0Input.setPlaceholderText(_translate("MainWindow", "X0"))
        self.betaRInput.setPlaceholderText(_translate("MainWindow", "Right border"))
        self.betaStep.setPlaceholderText(_translate("MainWindow", "Step"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

